// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol_shop.proto

#include "protocol_shop.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace Protocol {
class C2S_ShopLoadDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<C2S_ShopLoad> _instance;
} _C2S_ShopLoad_default_instance_;
class S2C_ShopLoadDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<S2C_ShopLoad> _instance;
} _S2C_ShopLoad_default_instance_;
class C2S_ShopBuyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<C2S_ShopBuy> _instance;
} _C2S_ShopBuy_default_instance_;
class S2C_ShopBuyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<S2C_ShopBuy> _instance;
} _S2C_ShopBuy_default_instance_;
}  // namespace Protocol
static void InitDefaultsscc_info_C2S_ShopBuy_protocol_5fshop_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Protocol::_C2S_ShopBuy_default_instance_;
    new (ptr) ::Protocol::C2S_ShopBuy();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Protocol::C2S_ShopBuy::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_C2S_ShopBuy_protocol_5fshop_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_C2S_ShopBuy_protocol_5fshop_2eproto}, {}};

static void InitDefaultsscc_info_C2S_ShopLoad_protocol_5fshop_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Protocol::_C2S_ShopLoad_default_instance_;
    new (ptr) ::Protocol::C2S_ShopLoad();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Protocol::C2S_ShopLoad::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_C2S_ShopLoad_protocol_5fshop_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_C2S_ShopLoad_protocol_5fshop_2eproto}, {}};

static void InitDefaultsscc_info_S2C_ShopBuy_protocol_5fshop_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Protocol::_S2C_ShopBuy_default_instance_;
    new (ptr) ::Protocol::S2C_ShopBuy();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Protocol::S2C_ShopBuy::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_S2C_ShopBuy_protocol_5fshop_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_S2C_ShopBuy_protocol_5fshop_2eproto}, {}};

static void InitDefaultsscc_info_S2C_ShopLoad_protocol_5fshop_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Protocol::_S2C_ShopLoad_default_instance_;
    new (ptr) ::Protocol::S2C_ShopLoad();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Protocol::S2C_ShopLoad::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_S2C_ShopLoad_protocol_5fshop_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_S2C_ShopLoad_protocol_5fshop_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_protocol_5fshop_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_protocol_5fshop_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_protocol_5fshop_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_protocol_5fshop_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_ShopLoad, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_ShopLoad, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_ShopBuy, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_ShopBuy, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Protocol::C2S_ShopLoad)},
  { 5, -1, sizeof(::Protocol::S2C_ShopLoad)},
  { 10, -1, sizeof(::Protocol::C2S_ShopBuy)},
  { 15, -1, sizeof(::Protocol::S2C_ShopBuy)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Protocol::_C2S_ShopLoad_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Protocol::_S2C_ShopLoad_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Protocol::_C2S_ShopBuy_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Protocol::_S2C_ShopBuy_default_instance_),
};

const char descriptor_table_protodef_protocol_5fshop_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023protocol_shop.proto\022\010Protocol\"\016\n\014C2S_S"
  "hopLoad\"\016\n\014S2C_ShopLoad\"\r\n\013C2S_ShopBuy\"\r"
  "\n\013S2C_ShopBuyb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_protocol_5fshop_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_protocol_5fshop_2eproto_sccs[4] = {
  &scc_info_C2S_ShopBuy_protocol_5fshop_2eproto.base,
  &scc_info_C2S_ShopLoad_protocol_5fshop_2eproto.base,
  &scc_info_S2C_ShopBuy_protocol_5fshop_2eproto.base,
  &scc_info_S2C_ShopLoad_protocol_5fshop_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_protocol_5fshop_2eproto_once;
static bool descriptor_table_protocol_5fshop_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protocol_5fshop_2eproto = {
  &descriptor_table_protocol_5fshop_2eproto_initialized, descriptor_table_protodef_protocol_5fshop_2eproto, "protocol_shop.proto", 101,
  &descriptor_table_protocol_5fshop_2eproto_once, descriptor_table_protocol_5fshop_2eproto_sccs, descriptor_table_protocol_5fshop_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_protocol_5fshop_2eproto::offsets,
  file_level_metadata_protocol_5fshop_2eproto, 4, file_level_enum_descriptors_protocol_5fshop_2eproto, file_level_service_descriptors_protocol_5fshop_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_protocol_5fshop_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_protocol_5fshop_2eproto), true);
namespace Protocol {

// ===================================================================

void C2S_ShopLoad::InitAsDefaultInstance() {
}
class C2S_ShopLoad::_Internal {
 public:
};

C2S_ShopLoad::C2S_ShopLoad()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Protocol.C2S_ShopLoad)
}
C2S_ShopLoad::C2S_ShopLoad(const C2S_ShopLoad& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_ShopLoad)
}

void C2S_ShopLoad::SharedCtor() {
}

C2S_ShopLoad::~C2S_ShopLoad() {
  // @@protoc_insertion_point(destructor:Protocol.C2S_ShopLoad)
  SharedDtor();
}

void C2S_ShopLoad::SharedDtor() {
}

void C2S_ShopLoad::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const C2S_ShopLoad& C2S_ShopLoad::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_C2S_ShopLoad_protocol_5fshop_2eproto.base);
  return *internal_default_instance();
}


void C2S_ShopLoad::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C2S_ShopLoad)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

const char* C2S_ShopLoad::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* C2S_ShopLoad::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C2S_ShopLoad)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C2S_ShopLoad)
  return target;
}

size_t C2S_ShopLoad::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C2S_ShopLoad)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void C2S_ShopLoad::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Protocol.C2S_ShopLoad)
  GOOGLE_DCHECK_NE(&from, this);
  const C2S_ShopLoad* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<C2S_ShopLoad>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Protocol.C2S_ShopLoad)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Protocol.C2S_ShopLoad)
    MergeFrom(*source);
  }
}

void C2S_ShopLoad::MergeFrom(const C2S_ShopLoad& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C2S_ShopLoad)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void C2S_ShopLoad::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Protocol.C2S_ShopLoad)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2S_ShopLoad::CopyFrom(const C2S_ShopLoad& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C2S_ShopLoad)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_ShopLoad::IsInitialized() const {
  return true;
}

void C2S_ShopLoad::InternalSwap(C2S_ShopLoad* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_ShopLoad::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void S2C_ShopLoad::InitAsDefaultInstance() {
}
class S2C_ShopLoad::_Internal {
 public:
};

S2C_ShopLoad::S2C_ShopLoad()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Protocol.S2C_ShopLoad)
}
S2C_ShopLoad::S2C_ShopLoad(const S2C_ShopLoad& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_ShopLoad)
}

void S2C_ShopLoad::SharedCtor() {
}

S2C_ShopLoad::~S2C_ShopLoad() {
  // @@protoc_insertion_point(destructor:Protocol.S2C_ShopLoad)
  SharedDtor();
}

void S2C_ShopLoad::SharedDtor() {
}

void S2C_ShopLoad::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const S2C_ShopLoad& S2C_ShopLoad::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_S2C_ShopLoad_protocol_5fshop_2eproto.base);
  return *internal_default_instance();
}


void S2C_ShopLoad::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S2C_ShopLoad)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

const char* S2C_ShopLoad::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* S2C_ShopLoad::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S2C_ShopLoad)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S2C_ShopLoad)
  return target;
}

size_t S2C_ShopLoad::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S2C_ShopLoad)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void S2C_ShopLoad::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Protocol.S2C_ShopLoad)
  GOOGLE_DCHECK_NE(&from, this);
  const S2C_ShopLoad* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<S2C_ShopLoad>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Protocol.S2C_ShopLoad)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Protocol.S2C_ShopLoad)
    MergeFrom(*source);
  }
}

void S2C_ShopLoad::MergeFrom(const S2C_ShopLoad& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S2C_ShopLoad)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void S2C_ShopLoad::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Protocol.S2C_ShopLoad)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2C_ShopLoad::CopyFrom(const S2C_ShopLoad& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S2C_ShopLoad)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2C_ShopLoad::IsInitialized() const {
  return true;
}

void S2C_ShopLoad::InternalSwap(S2C_ShopLoad* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata S2C_ShopLoad::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void C2S_ShopBuy::InitAsDefaultInstance() {
}
class C2S_ShopBuy::_Internal {
 public:
};

C2S_ShopBuy::C2S_ShopBuy()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Protocol.C2S_ShopBuy)
}
C2S_ShopBuy::C2S_ShopBuy(const C2S_ShopBuy& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_ShopBuy)
}

void C2S_ShopBuy::SharedCtor() {
}

C2S_ShopBuy::~C2S_ShopBuy() {
  // @@protoc_insertion_point(destructor:Protocol.C2S_ShopBuy)
  SharedDtor();
}

void C2S_ShopBuy::SharedDtor() {
}

void C2S_ShopBuy::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const C2S_ShopBuy& C2S_ShopBuy::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_C2S_ShopBuy_protocol_5fshop_2eproto.base);
  return *internal_default_instance();
}


void C2S_ShopBuy::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C2S_ShopBuy)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

const char* C2S_ShopBuy::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* C2S_ShopBuy::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C2S_ShopBuy)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C2S_ShopBuy)
  return target;
}

size_t C2S_ShopBuy::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C2S_ShopBuy)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void C2S_ShopBuy::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Protocol.C2S_ShopBuy)
  GOOGLE_DCHECK_NE(&from, this);
  const C2S_ShopBuy* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<C2S_ShopBuy>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Protocol.C2S_ShopBuy)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Protocol.C2S_ShopBuy)
    MergeFrom(*source);
  }
}

void C2S_ShopBuy::MergeFrom(const C2S_ShopBuy& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C2S_ShopBuy)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void C2S_ShopBuy::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Protocol.C2S_ShopBuy)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2S_ShopBuy::CopyFrom(const C2S_ShopBuy& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C2S_ShopBuy)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_ShopBuy::IsInitialized() const {
  return true;
}

void C2S_ShopBuy::InternalSwap(C2S_ShopBuy* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_ShopBuy::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void S2C_ShopBuy::InitAsDefaultInstance() {
}
class S2C_ShopBuy::_Internal {
 public:
};

S2C_ShopBuy::S2C_ShopBuy()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Protocol.S2C_ShopBuy)
}
S2C_ShopBuy::S2C_ShopBuy(const S2C_ShopBuy& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_ShopBuy)
}

void S2C_ShopBuy::SharedCtor() {
}

S2C_ShopBuy::~S2C_ShopBuy() {
  // @@protoc_insertion_point(destructor:Protocol.S2C_ShopBuy)
  SharedDtor();
}

void S2C_ShopBuy::SharedDtor() {
}

void S2C_ShopBuy::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const S2C_ShopBuy& S2C_ShopBuy::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_S2C_ShopBuy_protocol_5fshop_2eproto.base);
  return *internal_default_instance();
}


void S2C_ShopBuy::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S2C_ShopBuy)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

const char* S2C_ShopBuy::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* S2C_ShopBuy::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S2C_ShopBuy)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S2C_ShopBuy)
  return target;
}

size_t S2C_ShopBuy::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S2C_ShopBuy)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void S2C_ShopBuy::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Protocol.S2C_ShopBuy)
  GOOGLE_DCHECK_NE(&from, this);
  const S2C_ShopBuy* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<S2C_ShopBuy>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Protocol.S2C_ShopBuy)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Protocol.S2C_ShopBuy)
    MergeFrom(*source);
  }
}

void S2C_ShopBuy::MergeFrom(const S2C_ShopBuy& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S2C_ShopBuy)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void S2C_ShopBuy::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Protocol.S2C_ShopBuy)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2C_ShopBuy::CopyFrom(const S2C_ShopBuy& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S2C_ShopBuy)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2C_ShopBuy::IsInitialized() const {
  return true;
}

void S2C_ShopBuy::InternalSwap(S2C_ShopBuy* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata S2C_ShopBuy::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::C2S_ShopLoad* Arena::CreateMaybeMessage< ::Protocol::C2S_ShopLoad >(Arena* arena) {
  return Arena::CreateInternal< ::Protocol::C2S_ShopLoad >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_ShopLoad* Arena::CreateMaybeMessage< ::Protocol::S2C_ShopLoad >(Arena* arena) {
  return Arena::CreateInternal< ::Protocol::S2C_ShopLoad >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C2S_ShopBuy* Arena::CreateMaybeMessage< ::Protocol::C2S_ShopBuy >(Arena* arena) {
  return Arena::CreateInternal< ::Protocol::C2S_ShopBuy >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_ShopBuy* Arena::CreateMaybeMessage< ::Protocol::S2C_ShopBuy >(Arena* arena) {
  return Arena::CreateInternal< ::Protocol::S2C_ShopBuy >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
